### PR TITLE
Add speakers and thier images 

### LINKED ISSUE #2: Let's add the speakers to the Conference website
We need to add the speakers to the conference website. To do it, we need to add a md file in the `content\speakers` folder using this same format:  https://github.com/GDGToulouse/site-devfest-2019/blob/master/content/speakers/adrien_anceau.md

We'll need to add the talks as well. To do it so we'll add a md file to the `content\sessions` folder following this format: https://github.com/GDGToulouse/site-devfest-2019/blob/master/content/sessions/10_est_une_puissance_de_2.md

We have 8 Speakers and 9 talks, in total. The interested contributor will receive the details in a separate email.

### PR DESCRIPTION
**Pull request by AQIB-NAWAB**
Closes #2 

Add the speakers into page 

Here is the output 

image

image

### CODE REVIEW

**Comment by AQIB-NAWAB** [comment]
fix  #2

**Comment by benjagm** [comment]
Hi @AQIB-NAWAB Have you added the agenda?

**Comment by AQIB-NAWAB** [comment]
> Hi @AQIB-NAWAB Have you added the agenda?

No

**Comment by benjagm** [comment]
> > Hi @AQIB-NAWAB Have you added the agenda?
> 
> No

No problem. Just checking. I am working on it now

**Comment by AQIB-NAWAB** [comment]
> > > Hi @AQIB-NAWAB Have you added the agenda?
> > 
> > 
> > No
> 
> No problem. Just checking. I am working on it now

Thanks , Actually my laptop was stolen two days ago , i will try to add Agenda as soon as possible

**Comment by benjagm** [comment]
Sorry for your laptop I hope police can make something about it.. Dont worry about the agenda. I am working on it.

**Pull request merged**
