### PR TITLE
update speaker page

### LINKED ISSUE #22: Update speakers page
Update the [speaker's line-up](https://conference.json-schema.org/sessions/) to reflect the last-minute changes we had during the conference. The full list of speakers is the following:

- JSON Schema for data design and contract, client and code generation by Tom Collins (DVLA, UK Gov)
- IEC Standards: Toward Digital Standards with JSON Schema by Thomas Clark (Octue CEO, conference sponsor)
- Introducing Strands - a JSON Schema repository by Thomas Clark
- JSON Schema: powering FINOS architecture as code by James Gough (FINOS)
- Generic and extensible web of things manager using JSON Schema and AI by Andreas Eberhart (Dashjoin, ambassador)
- High-performance JSON Schema validation in .NET by Matthew Adams (Endjin, TSC member)
- JSON schema and relational databases: bridging the gap by Loic Lefèvre (Oracle)
-Applying software engineering practices to JSON Schemas by Juan Cruz Viotti (Sourcemeta CEO, TSC member)
- The state of JSON schema by Benjamin Granados (Celonis, TSC member)

Also add the slide decks, which are available as PDF files, in this PR. 

If you want to work on this issue, please reach out to Valeria Hernandez on the JSON Schema Slack workspace, so she can share the files with you. 

Thank you.

### PR DESCRIPTION
**Pull request by techmannih**
close #22

### CODE REVIEW

**Comment by Honyii** [comment]
@techmannih thanks for the task done, however there is an inconsistency to the presentation title. The expectation is that the title should be in sentence case i.e;

a. State of JSON Schema 
b. IEC Standards: Toward Digital Standards with JSON Schema 
c. Applying Software Engineering Practices to JSON Schemas 
d. High Performance JSON Schema Validation in .NET
e. JSON Schema and Relational Databases: Bridging the Gap! 
f. Unlocking Dynamic Frontend Development Through JSON Schema 
g. Introducing Strands - A JSONSchema Repository
h. Generic and Extensible Web of Things Manager Using JSON Schema & AI 
i. JSON Schema for Data Design and Contract, Client, and Code Generation 
j. JSON Schema: Powering FINOS Architecture as Code

2. Capitalizing "Ambassador" in content/speakers/andreas.md.
3. The presentation slide should be in the static folder of the repo in a subfolder and not a dropbox link. 
cc @benjagm can you explain further on this for more clarification.

**Comment by Honyii** [comment]
@techmannih so it has to do with the way you are referencing the pdf file. Here is how you can resolve this;
- We have an existing static folder 
- Create another folder where you'd store all pdfs
- Now go to the sessions folder and reference it there, for example you want to reference the presentation for "IEC Standards - Toward digital standards with JSONSchema."
- It should be "presentation: /{{the folder name where all pdfs are stored}}/{{name of the pdf file}}".

This should fix the referencing blocker and for more clarification, you can check the screenshot shared here to use as an example structure.

Screenshot 2024-12-17 at 18 59 38
Screenshot 2024-12-17 at 18 59 48

**Comment by Honyii** [comment]
That's weird, I just followed the steps I shared and it's working on my end. We can have a short call tomorrow and figure out why yours is failing if you do not mind.

**Comment by Honyii** [comment]
Looks good on my end and
Cc @benjagm @DhairyaMajmudar can have a second look incase anything was missed.

**Comment by DhairyaMajmudar** [comment]
Thank you so much @Honyii for the review 

Amazing PR @techmannih listing some suggestions to work upon

1. In some speaker session pages the slide tab is getting merged with footer. You can fix this by adding some bottom margin 

image
  
2. The avatar image of James Gough is missing 

image

3. Let's keep the card of Neha Singla to be squared-shaped maintaining the consistency with the grid.

image

4. I'm getting a completely blank presentation slide for Tom Collins's Talk. Pls. confirm if you're facing the same

**Pull request merged**
